### ISSUE TITLE
add react node types for HomebaseProvider

### ISSUE THREAD

**Issue by shrugs** [homebaseio/homebase-react#45]
i'm not sure how to implement this (hence issue instead of PR), but a quick QoL update would be to include the react typings for the homebase provider component type here

https://github.com/homebaseio/homebase-react/blob/master/types/index.d.ts#L97

probably like

```ts
export function HomebaseProvider(props: {config?:config, children:React.ReactNode}): React.ReactElement;
```

**Comment by smothers** [comment]
Thanks @shrugs and @rubinovitz. Looks like this has landed.
