### ISSUE TITLE
Examples don't use custom formatter for dev tools

### ISSUE THREAD

**Issue by saoirse-zee** [homebaseio/homebase-react#86]
Hi there! I just started with the tutorial and got stumped on the custom formatters. My entity console.logs looked like the old, rather unreadable style. It took me a bit of time to figure out why.

I eventually realized that the examples in the repo use an earlier version of homebase-react. I bumped the version [here](https://github.com/homebaseio/homebase-react/blob/0149d9b0948fbef2ea8949380d394e9c4a37cb1a/examples/todo/package.json#L9) to `0.5.4` and -- voila -- suddenly my browser console matched the tutorial.

I'm no longer stuck, but just thought I'd post an issue in case others run into the same thing. For anyone using the examples as a starting point, it could be helpful to bump the version so that the custom formatters work out of the box.

**Comment by smothers** [comment]
Thanks so much @saoirse-zee, this is certainly an oversight. Sorry we missed these. 

If you’ve got a moment feel free to bump them, otherwise I’ll get to it in a bit.
